spring:
  cloud:
    service-registry:
      auto-registration:
        enabled: true
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        service: storage
        group: DEFAULT_GROUP
        namespace: prd
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/af_storage
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver