spring:
  profiles:
    active: prod
  application:
    name: af-storage
  cloud:
    service-registry:
      auto-registration:
        enabled: true
    nacos:
      username: nacos
      password: nacos
  datasource:
    username: root
    password: Anonymous1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true  # 开启Flyway
    locations: classpath:db/migration  # 脚本存放目录
    baseline-on-migrate: true  # 首次使用时，若数据库已有表，自动创建基线
    clean-disabled: true  # 禁用clean命令
    encoding: UTF-8  # 脚本编码
    baseline-version: 0  # 基线版本

org:
  anonymous:
    root-save-path: "anonymous"
    image-save-path: "images"
    thumbnail-save-path: "thumbnails"
server:
  port: 8080
